# Generated by Django 4.0.2 on 2022-02-17 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee1',
        ),
    ]
